[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Tự động cài đặt 4 thư viện cần thiết cho các cảm biến
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
    claws/BH1750 @ ^1.3.0
    milesburton/DallasTemperature @ ^3.11.0
    paulstoffregen/OneWire @ ^2.3.7

[platformio]
; Báo cho PlatformIO biết code nằm ngay trong thư mục này thay vì phải tạo folder 'src'
src_dir = .
